CREATE DATABASE IF NOT EXISTS AULA2805;

USE AULA2805;

CREATE TABLE MEDICO(
    numeroCrm BIGINT NOT NULL,
    estado CHAR(2) NOT NULL,
    nomeCompleto VARCHAR(50) NOT NULL,

    CONSTRAINT MEDICO_PK PRIMARY KEY (numeroCrm, estado),
    CONSTRAINT MEDICO_UK UNIQUE (numeroCrm, estado)

)ENGINE = INNODB;

CREATE TABLE ESPECIALIDADE(
	idEspecialidade INT NOT NULL AUTO_INCREMENT,
    nomeEspecialidade varchar(20) NOT NULL,
    
    CONSTRAINT ESPECIALIDADE_PK PRIMARY KEY (idEspecialidade)
) ENGINE = INNODB;    

CREATE TABLE ESPECIALIDADECLINICA(
	numeroCrm BIGINT NOT NULL,
    estado CHAR(2) NOT NULL,
    idEspecialidade INT NOT NULL AUTO_INCREMENT,
    
    CONSTRAINT ESPECIALIDADE_MEDICO_FK FOREIGN KEY (numeroCrm, estado) REFERENCES MEDICO(numeroCrm, estado) ON DELETE CASCADE,
    CONSTRAINT ESPECIALIDADE_FK FOREIGN KEY (idEspecialidade) REFERENCES ESPECIALIDADE(idEspecialidade) ON DELETE CASCADE
) ENGINE = INNODB;    

CREATE TABLE PACIENTE (
	idPaciente INT NOT NULL auto_increment,
    nomeCompleto VARCHAR(50) NOT NULL,
    dataNascimento DATE NOT NULL,
    sexo ENUM('F', 'M') NOT NULL,
    rua VARCHAR(40) NOT NULL,
    numero VARCHAR(5) NOT NULL,
    bairro VARCHAR(40) NOT NULL,
    cidade VARCHAR(40) NOT NULL,
    estado CHAR(2) NOT NULL,
    complemento VARCHAR(100),
    cep DECIMAL(8,0) NOT NULL,
    
    CONSTRAINT PACIENTE_PK primary key (idPaciente)
) ENGINE = INNODB;

CREATE TABLE TELEFONEPACIENTE(
	idPaciente INT NOT NULL,
    telefonePaciente DECIMAL (11,0) NOT NULL,
    
    CONSTRAINT telefone_PACIENTE_FK FOREIGN KEY (idPaciente) REFERENCES PACIENTE (idPaciente) ON DELETE CASCADE
) ENGINE = INNODB;

CREATE TABLE CONSULTA(
	idConsulta INT NOT NULL AUTO_INCREMENT,
    dataConsulta DATETIME NOT NULL,
    numeroCrm BIGINT NOT NULL,
    estado CHAR(2) NOT NULL,
    idPaciente INT NOT NULL,
    
    CONSTRAINT CONSULTA_PK primary key (idConsulta),
    CONSTRAINT CONSULTA_MEDICO_FK foreign key (numeroCrm, estado) references MEDICO (numeroCrm, estado) ON DELETE CASCADE,
    CONSTRAINT CONSULTA_PACIENTE_FK FOREIGN KEY (idPaciente) REFERENCES PACIENTE(idPaciente) ON DELETE CASCADE
) ENGINE = INNODB;

CREATE TABLE RECEITA(
	idReceita INT NOT NULL AUTO_INCREMENT,
    idConsulta  INT NOT NULL,
    descricao VARCHAR(200) NOT NULL,
    
    CONSTRAINT RECEITA_PK PRIMARY KEY (idReceita),
    CONSTRAINT RECEITA_CONSULTA_FK FOREIGN KEY (idConsulta) REFERENCES CONSULTA (idConsulta) ON DELETE CASCADE
)ENGINE = INNODB;
